chore(deps-dev): Bump esbuild from 0.11.5 to 0.11.6 (#416)
Bumps [esbuild](https://github.com/evanw/esbuild) from 0.11.5 to 0.11.6.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/evanw/esbuild/releases">esbuild's releases</a>.</em></p>
<blockquote>
<h2>v0.11.6</h2>
<ul>
<li>
<p>Fix an incorrect minification transformation (<a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/1121">#1121</a>)</p>
<p>This release removes an incorrect substitution rule in esbuild's peephole optimizer, which is run when minification is enabled. The incorrect rule transformed <code>if(a &amp;&amp; falsy)</code> into <code>if(a, falsy)</code> which is equivalent if <code>falsy</code> has no side effects (such as the literal <code>false</code>). However, the rule didn't check that the expression is side-effect free first which could result in miscompiled code. I have removed the rule instead of modifying it to check for the lack of side effects first because while the code is slightly smaller, it may also be more expensive at run-time which is undesirable. The size savings are also very insignificant.</p>
</li>
<li>
<p>Change how <code>NODE_PATH</code> works to match node (<a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/1117">#1117</a>)</p>
<p>Node searches for packages in nearby <code>node_modules</code> directories, but it also allows you to inject extra directories to search for packages in using the <code>NODE_PATH</code> environment variable. This is supported when using esbuild's CLI as well as via the <code>nodePaths</code> option when using esbuild's API.</p>
<p>Node's module resolution algorithm is well-documented, and esbuild's path resolution is designed to follow it. The full algorithm is here: <a href="https://nodejs.org/api/modules.html#modules_all_together">https://nodejs.org/api/modules.html#modules_all_together</a>. However, it appears that the documented algorithm is incorrect with regard to <code>NODE_PATH</code>. The documentation says <code>NODE_PATH</code> directories should take precedence over <code>node_modules</code> directories, and so that's how esbuild worked. However, in practice node actually does it the other way around.</p>
<p>Starting with this release, esbuild will now allow <code>node_modules</code> directories to take precedence over <code>NODE_PATH</code> directories. This is a deviation from the published algorithm.</p>
</li>
<li>
<p>Provide a better error message for incorrectly-quoted JSX attributes (<a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/959">#959</a>, <a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/1115">#1115</a>)</p>
<p>People sometimes try to use the output of <code>JSON.stringify()</code> as a JSX attribute when automatically-generating JSX code. Doing so is incorrect because JSX strings work like XML instead of like JS (since JSX is XML-in-JS). Specifically, using a backslash before a quote does not cause it to be escaped:</p>
<pre lang="jsx"><code>//     JSX ends the &quot;content&quot; attribute here and sets &quot;content&quot; to 'some so-called \\'
//                                            v
let button = &lt;Button content=&quot;some so-called \&quot;button text\&quot;&quot; /&gt;
//                                                        ^
//         There is no &quot;=&quot; after the JSX attribute &quot;text&quot;, so we expect a &quot;&gt;&quot;
</code></pre>
<p>It's not just esbuild; Babel and TypeScript also treat this as a syntax error. All of these JSX parsers are just following <a href="https://facebook.github.io/jsx/">the JSX specification</a>. This has come up twice now so it could be worth having a dedicated error message. Previously esbuild had a generic syntax error like this:</p>
<pre><code> &gt; example.jsx:1:58: error: Expected &quot;&gt;&quot; but found &quot;\\&quot;
    1 │ let button = &lt;Button content=&quot;some so-called \&quot;button text\&quot;&quot; /&gt;
      ╵                                                           ^
</code></pre>
<p>Now esbuild will provide more information if it detects this case:</p>
<pre><code> &gt; example.jsx:1:58: error: Unexpected backslash in JSX element
    1 │ let button = &lt;Button content=&quot;some so-called \&quot;button text\&quot;&quot; /&gt;
      ╵                                                           ^
   example.jsx:1:45: note: Quoted JSX attributes use XML-style escapes instead of JavaScript-style escapes
    1 │ let button = &lt;Button content=&quot;some so-called \&quot;button text\&quot;&quot; /&gt;
      │                                              ~~
      ╵                                              &amp;quot;
   example.jsx:1:29: note: Consider using a JavaScript string inside {...} instead of a quoted JSX attribute
    1 │ let button = &lt;Button content=&quot;some so-called \&quot;button text\&quot;&quot; /&gt;
      │                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      ╵                              {&quot;some so-called \&quot;button text\&quot;&quot;}
</code></pre>
</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/evanw/esbuild/blob/master/CHANGELOG.md">esbuild's changelog</a>.</em></p>
<blockquote>
<h2>0.11.6</h2>
<ul>
<li>
<p>Fix an incorrect minification transformation (<a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/1121">#1121</a>)</p>
<p>This release removes an incorrect substitution rule in esbuild's peephole optimizer, which is run when minification is enabled. The incorrect rule transformed <code>if(a &amp;&amp; falsy)</code> into <code>if(a, falsy)</code> which is equivalent if <code>falsy</code> has no side effects (such as the literal <code>false</code>). However, the rule didn't check that the expression is side-effect free first which could result in miscompiled code. I have removed the rule instead of modifying it to check for the lack of side effects first because while the code is slightly smaller, it may also be more expensive at run-time which is undesirable. The size savings are also very insignificant.</p>
</li>
<li>
<p>Change how <code>NODE_PATH</code> works to match node (<a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/1117">#1117</a>)</p>
<p>Node searches for packages in nearby <code>node_modules</code> directories, but it also allows you to inject extra directories to search for packages in using the <code>NODE_PATH</code> environment variable. This is supported when using esbuild's CLI as well as via the <code>nodePaths</code> option when using esbuild's API.</p>
<p>Node's module resolution algorithm is well-documented, and esbuild's path resolution is designed to follow it. The full algorithm is here: <a href="https://nodejs.org/api/modules.html#modules_all_together">https://nodejs.org/api/modules.html#modules_all_together</a>. However, it appears that the documented algorithm is incorrect with regard to <code>NODE_PATH</code>. The documentation says <code>NODE_PATH</code> directories should take precedence over <code>node_modules</code> directories, and so that's how esbuild worked. However, in practice node actually does it the other way around.</p>
<p>Starting with this release, esbuild will now allow <code>node_modules</code> directories to take precedence over <code>NODE_PATH</code> directories. This is a deviation from the published algorithm.</p>
</li>
<li>
<p>Provide a better error message for incorrectly-quoted JSX attributes (<a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/959">#959</a>, <a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/1115">#1115</a>)</p>
<p>People sometimes try to use the output of <code>JSON.stringify()</code> as a JSX attribute when automatically-generating JSX code. Doing so is incorrect because JSX strings work like XML instead of like JS (since JSX is XML-in-JS). Specifically, using a backslash before a quote does not cause it to be escaped:</p>
<pre lang="jsx"><code>//     JSX ends the &quot;content&quot; attribute here and sets &quot;content&quot; to 'some so-called \\'
//                                            v
let button = &lt;Button content=&quot;some so-called \&quot;button text\&quot;&quot; /&gt;
//                                                        ^
//         There is no &quot;=&quot; after the JSX attribute &quot;text&quot;, so we expect a &quot;&gt;&quot;
</code></pre>
<p>It's not just esbuild; Babel and TypeScript also treat this as a syntax error. All of these JSX parsers are just following <a href="https://facebook.github.io/jsx/">the JSX specification</a>. This has come up twice now so it could be worth having a dedicated error message. Previously esbuild had a generic syntax error like this:</p>
<pre><code> &gt; example.jsx:1:58: error: Expected &quot;&gt;&quot; but found &quot;\\&quot;
    1 │ let button = &lt;Button content=&quot;some so-called \&quot;button text\&quot;&quot; /&gt;
      ╵                                                           ^
</code></pre>
<p>Now esbuild will provide more information if it detects this case:</p>
<pre><code> &gt; example.jsx:1:58: error: Unexpected backslash in JSX element
    1 │ let button = &lt;Button content=&quot;some so-called \&quot;button text\&quot;&quot; /&gt;
      ╵                                                           ^
   example.jsx:1:45: note: Quoted JSX attributes use XML-style escapes instead of JavaScript-style escapes
    1 │ let button = &lt;Button content=&quot;some so-called \&quot;button text\&quot;&quot; /&gt;
      │                                              ~~
      ╵                                              &amp;quot;
   example.jsx:1:29: note: Consider using a JavaScript string inside {...} instead of a quoted JSX attribute
    1 │ let button = &lt;Button content=&quot;some so-called \&quot;button text\&quot;&quot; /&gt;
      │                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      ╵                              {&quot;some so-called \&quot;button text\&quot;&quot;}
</code></pre>
</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/evanw/esbuild/commit/d16c6190b455bce5e3385c3d8086ae51e66053f6"><code>d16c619</code></a> publish 0.11.6 to npm</li>
<li><a href="https://github.com/evanw/esbuild/commit/0ffaab1cc1275383679e1a4266f02a9c04e78209"><code>0ffaab1</code></a> some small changes to release notes</li>
<li><a href="https://github.com/evanw/esbuild/commit/ef9d29e0a466ade11f022189bfd4d3101d3217d7"><code>ef9d29e</code></a> fix <a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/1121">#1121</a>: remove a bad peephole minification</li>
<li><a href="https://github.com/evanw/esbuild/commit/99b260670b18676b7ba9af3b03d1d0821a7ddde2"><code>99b2606</code></a> fix <a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/1115">#1115</a>: add a special-cased error message</li>
<li><a href="https://github.com/evanw/esbuild/commit/5dc64cb97bdb99238cb19054a4aa4e41ddd04cd7"><code>5dc64cb</code></a> fix <a href="https://github-redirect.dependabot.com/evanw/esbuild/issues/1117">#1117</a>: check &quot;node_modules&quot; before &quot;NODE_PATH&quot;</li>
<li>See full diff in <a href="https://github.com/evanw/esbuild/compare/v0.11.5...v0.11.6">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=esbuild&package-manager=npm_and_yarn&previous-version=0.11.5&new-version=0.11.6)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually


</details>